--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as Revenue
From dbo.updated_data
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
From dbo.updated_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from dbo.updated_data)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(CAST(review_rating AS float)), 0) AS [Average Product Rating]
FROM dbo.updated_data
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS float)) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, AVG(purchase_amount) as average_purchase
FROM dbo.updated_data
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
    COUNT(customer_id) as total_count,
    AVG(purchase_amount) as avg_spend,
    SUM(purchase_amount) as total_revanue
FROM dbo.updated_data
group by subscription_status
order by total_revanue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5
       item_purchased,
       ROUND(AVG(CASE WHEN discount_applied = 'Yes' THEN 100.0 ELSE 0.0 END), 0) AS discount_rate
FROM dbo.updated_data
GROUP BY item_purchased
ORDER BY discount_rate DESc;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id,previous_purchases,
       CASE When previous_purchases > 10 then 'Loyal Customer'
            When previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            Else 'New'
            END AS customer_segment
FROM dbo.updated_data
)
select customer_segment, COUNT(*) as 'Number of Customers'
FROM customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM dbo.updated_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
FROM dbo.updated_data
Where previous_purchases > 5
Group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group,
       SUM(purchase_amount) AS revanue
FROM dbo.updated_data
Group by age_group
order by revanue;





       

       


        


